name: Build Plugin ZIP

on:
  push:
    branches:
      - main # Adjust to the branch you want to trigger this workflow on
      - master
      - dev
      - action
      - release

  pull_request:
    branches:
      - main # Adjust to the branch you want to trigger this workflow on
      - master
      - dev
      - action
      - release

jobs:
  build:
    name: Build Plugin ZIP
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Generate the ZIP file
      - name: Create Plugin ZIP
        run: |
          mkdir -p build
          zip -r build/group-events-for-buddyboss.zip . \
          -x "*.git*" "*.github*" "build/*"

      # Upload the ZIP as an artifact (optional)
      - name: Upload Plugin ZIP
        uses: actions/upload-artifact@v4
        with:
          name: GrowwBuddyPlugin
          path: build/group-events-for-buddyboss.zip

        env:
          CI: true